//! Trust roots for the federated relay network.
//!
//! Contains the authority public keys that define which relays are trusted.
//! The build script (`build.rs`) generates `trust_roots_generated.rs` with
//! authority keys from the `AUTHORITY_PUBKEYS` env var. If the env var is
//! not set, dev-mode placeholder keys are generated instead.

use sha2::{Digest, Sha256};

// Generated by build.rs: AUTHORITY_PUBKEYS and AUTHORITY_THRESHOLD constants.
// When AUTHORITY_PUBKEYS env var is set at build time, those keys are used.
// Otherwise, dev-mode placeholder keys ([0x01;32], [0x02;32], [0x03;32]) are generated.
include!(concat!(env!("OUT_DIR"), "/trust_roots_generated.rs"));

/// Compute the network identity: SHA-256 of sorted authority pubkeys.
pub fn network_id() -> [u8; 32] {
    let mut sorted = AUTHORITY_PUBKEYS.to_vec();
    sorted.sort();
    let mut hasher = Sha256::new();
    for key in &sorted {
        hasher.update(key);
    }
    hasher.finalize().into()
}

/// Check if a public key is a trusted authority.
pub fn is_trusted_authority(pubkey: &[u8; 32]) -> bool {
    AUTHORITY_PUBKEYS.contains(pubkey)
}
