use std::env;
use std::fs;
use std::path::Path;

fn main() {
    println!("cargo:rerun-if-env-changed=AUTHORITY_PUBKEYS");
    println!("cargo:rerun-if-env-changed=AUTHORITY_THRESHOLD");

    let out_dir = env::var("OUT_DIR").unwrap();
    let dest_path = Path::new(&out_dir).join("trust_roots_generated.rs");

    let threshold: usize = env::var("AUTHORITY_THRESHOLD")
        .ok()
        .and_then(|s| s.parse().ok())
        .unwrap_or(2);

    let pubkeys: Vec<[u8; 32]> = match env::var("AUTHORITY_PUBKEYS") {
        Ok(val) if !val.is_empty() => val
            .split(',')
            .map(|hex_str| {
                let hex_str = hex_str.trim();
                assert_eq!(
                    hex_str.len(),
                    64,
                    "Each authority pubkey must be 64 hex chars, got {}",
                    hex_str.len()
                );
                let bytes: Vec<u8> = (0..32)
                    .map(|i| {
                        u8::from_str_radix(&hex_str[i * 2..i * 2 + 2], 16).unwrap_or_else(|e| {
                            panic!("Invalid hex in authority pubkey at byte {i}: {e}")
                        })
                    })
                    .collect();
                let mut arr = [0u8; 32];
                arr.copy_from_slice(&bytes);
                arr
            })
            .collect(),
        _ => {
            // Dev-mode placeholder keys
            vec![[0x01; 32], [0x02; 32], [0x03; 32]]
        }
    };

    let mut code = String::from("// Auto-generated by build.rs — do not edit\n");
    code.push_str("pub const AUTHORITY_PUBKEYS: &[[u8; 32]] = &[\n");
    for key in &pubkeys {
        code.push_str("    [");
        for (i, byte) in key.iter().enumerate() {
            if i > 0 {
                code.push_str(", ");
            }
            code.push_str(&format!("0x{byte:02x}"));
        }
        code.push_str("],\n");
    }
    code.push_str("];\n\n");
    code.push_str(&format!(
        "pub const AUTHORITY_THRESHOLD: usize = {threshold};\n"
    ));

    fs::write(&dest_path, code).unwrap();
}
