//! Federation verification types for WASM.
//!
//! Mirror types from `parolnet-relay::authority` for CBOR deserialization,
//! with verification implemented directly using `ed25519-dalek` and `sha2`.
//! This avoids pulling `parolnet-relay` (which depends on tokio/transport)
//! into the WASM build.

use ed25519_dalek::{Signature, Verifier, VerifyingKey};
use parolnet_protocol::address::PeerId;
use serde::{Deserialize, Serialize};
use sha2::{Digest, Sha256};

// Generated by build.rs: AUTHORITY_PUBKEYS and AUTHORITY_THRESHOLD constants.
include!(concat!(env!("OUT_DIR"), "/trust_roots_generated.rs"));

/// Compute the network identity: SHA-256 of sorted authority pubkeys.
pub fn network_id() -> [u8; 32] {
    let mut sorted = AUTHORITY_PUBKEYS.to_vec();
    sorted.sort();
    let mut hasher = Sha256::new();
    for key in &sorted {
        hasher.update(key);
    }
    hasher.finalize().into()
}

/// Serde helper for `[u8; 64]` arrays (signatures).
mod sig_bytes {
    use serde::{Deserialize, Deserializer, Serialize, Serializer};

    pub fn serialize<S: Serializer>(bytes: &[u8; 64], serializer: S) -> Result<S::Ok, S::Error> {
        serde_bytes::Bytes::new(bytes.as_slice()).serialize(serializer)
    }

    pub fn deserialize<'de, D: Deserializer<'de>>(deserializer: D) -> Result<[u8; 64], D::Error> {
        let v: Vec<u8> = serde_bytes::ByteBuf::deserialize(deserializer)?.into_vec();
        v.try_into().map_err(|v: Vec<u8>| {
            serde::de::Error::custom(format!("expected 64 bytes, got {}", v.len()))
        })
    }
}

/// A single authority's endorsement of a relay (mirror of `parolnet_relay::authority::AuthorityEndorsement`).
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct AuthorityEndorsement {
    pub authority_pubkey: [u8; 32],
    pub relay_peer_id: PeerId,
    pub endorsed_at: u64,
    pub expires_at: u64,
    #[serde(with = "sig_bytes")]
    pub signature: [u8; 64],
}

/// A signed relay descriptor (mirror of `parolnet_relay::directory::RelayDescriptor`).
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct RelayDescriptor {
    pub peer_id: PeerId,
    pub identity_key: [u8; 32],
    pub x25519_key: [u8; 32],
    pub addr: std::net::SocketAddr,
    pub bandwidth_class: u8,
    pub uptime_secs: u64,
    pub timestamp: u64,
    #[serde(with = "sig_bytes")]
    pub signature: [u8; 64],
    pub bandwidth_estimate: u64,
    pub next_pubkey: Option<[u8; 32]>,
}

/// A relay descriptor with authority endorsements (mirror of `parolnet_relay::authority::EndorsedDescriptor`).
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct EndorsedDescriptor {
    pub descriptor: RelayDescriptor,
    pub endorsements: Vec<AuthorityEndorsement>,
}

/// A complete signed directory snapshot from an authority (mirror of `parolnet_relay::authority::SignedDirectory`).
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct SignedDirectory {
    pub descriptors: Vec<EndorsedDescriptor>,
    pub timestamp: u64,
    pub authority_pubkey: [u8; 32],
    #[serde(with = "sig_bytes")]
    pub signature: [u8; 64],
}

/// Helper for CBOR-serializable directory content (without signature).
#[derive(Serialize)]
struct DirectorySignableContent<'a> {
    descriptors: &'a Vec<EndorsedDescriptor>,
    timestamp: u64,
}

impl AuthorityEndorsement {
    /// SHA-256 hash of (relay_peer_id || endorsed_at || expires_at).
    pub fn signable_bytes(&self) -> Vec<u8> {
        let mut hasher = Sha256::new();
        hasher.update(self.relay_peer_id.0);
        hasher.update(self.endorsed_at.to_be_bytes());
        hasher.update(self.expires_at.to_be_bytes());
        hasher.finalize().to_vec()
    }

    /// Verify the endorsement signature.
    pub fn verify(&self) -> Result<bool, String> {
        let verifying_key = VerifyingKey::from_bytes(&self.authority_pubkey)
            .map_err(|e| format!("invalid authority pubkey: {e}"))?;
        let signature = Signature::from_bytes(&self.signature);
        let signable = self.signable_bytes();
        Ok(verifying_key.verify(&signable, &signature).is_ok())
    }

    /// Check whether this endorsement has expired.
    pub fn is_expired(&self, now_secs: u64) -> bool {
        now_secs >= self.expires_at
    }
}

impl EndorsedDescriptor {
    /// Check that at least `threshold` valid, non-expired endorsements exist
    /// from distinct authorities in the trusted set.
    pub fn verify_threshold(
        &self,
        authority_pubkeys: &[[u8; 32]],
        threshold: usize,
        now_secs: u64,
    ) -> Result<bool, String> {
        let mut valid_authorities: Vec<[u8; 32]> = Vec::new();

        for endorsement in &self.endorsements {
            if !authority_pubkeys.contains(&endorsement.authority_pubkey) {
                continue;
            }
            if endorsement.is_expired(now_secs) {
                continue;
            }
            if !endorsement.verify()? {
                continue;
            }
            if endorsement.relay_peer_id != self.descriptor.peer_id {
                continue;
            }
            if !valid_authorities.contains(&endorsement.authority_pubkey) {
                valid_authorities.push(endorsement.authority_pubkey);
            }
        }

        Ok(valid_authorities.len() >= threshold)
    }
}

impl SignedDirectory {
    /// SHA-256 hash of CBOR-encoded (descriptors + timestamp).
    pub fn signable_bytes(&self) -> Vec<u8> {
        let content = DirectorySignableContent {
            descriptors: &self.descriptors,
            timestamp: self.timestamp,
        };
        let mut cbor_buf = Vec::new();
        ciborium::into_writer(&content, &mut cbor_buf)
            .expect("CBOR serialization should not fail for valid data");
        let mut hasher = Sha256::new();
        hasher.update(&cbor_buf);
        hasher.finalize().to_vec()
    }

    /// Verify the signing authority is in the trusted set and signature is valid.
    pub fn verify(&self, authority_pubkeys: &[[u8; 32]]) -> Result<bool, String> {
        if !authority_pubkeys.contains(&self.authority_pubkey) {
            return Ok(false);
        }

        let verifying_key = VerifyingKey::from_bytes(&self.authority_pubkey)
            .map_err(|e| format!("invalid authority pubkey: {e}"))?;
        let signature = Signature::from_bytes(&self.signature);
        let signable = self.signable_bytes();
        Ok(verifying_key.verify(&signable, &signature).is_ok())
    }
}
